### ISSUE TITLE
"red" variable in css

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#11]
In your css, why is the variable for hex code #336633 called red, but isn't red? I was thinking it might actually be better to make it actually red since it might be easier to differentiate incorrect answers from correct ones.

Now that I'm used to it, it doesn't bother me but when I first started using the app I did find it kinda hard to tell if I got an answer correct or not

**Comment by GoldenChrysus** [comment]
Hmm that's probably because of my protanopia color blindness. Don't worry about it; I'll figure it out.
