### ISSUE TITLE
I've noticed some inaccurate kimariji

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#12]
Due to the fact that the time the poems were written, hiragana wasn't fully standardized, sometimes the kimariji differs from the actual kana. While for the most part they're pretty similar there's a couple that vary pretty significantly, such as poem 44.

For the record I'm comparing to what's written on [this deck](https://www.amazon.com/gp/product/B001CIR6PG/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1), which is made by the company that makes the cards for official karuta matches and has the kimariji printed in red. I've went through all the poems and noted where these cards had a different kimariji listed

Poem 26:
  - Listed: をぐ
  - Actual: おぐ (I know this is pronounced the same, but it's written different on the card so I figured might as well include it)

Poem 39:
  - Listed: あさぢ
  - Actual: あさじ

Poem 42:
  - Listed: こひ
  - Actual: こい

Poem 43:
  - Listed: あひ
  - Actual: あい

Poem 44:
  - Listed: あふ
  - Actual: おおこ

Poem 45:
  - Listed: あはれ
  - Actual: あわれ

Poem 47:
  - Listed: やへ
  - Actual: やえ

Poem 60:
  - Listed: おほえ
  - Actual: おおえ

Poem 71:
  - Listed: ゆふ
  - Actual: ゆう

Poem 78:
  - Listed: あはぢ
  - Actual: あわじ

Poem 88:
  - Listed: なにはえ
  - Actual: なにわえ

Poem 95:
  - Listed: おほけ
  - Actual: おおけ

**Comment by GoldenChrysus** [comment]
Can you confirm if the Memrise deck has the correct kimariji? https://www.memrise.com/course/166253/charlottesville-karuta-societys-guide-to-kimariji/7/ I'll crosscheck them against there this weekend to update the incorrect ones, as I don't have a physical deck from that manufacturer.

**Comment by GoldenChrysus** [comment]
Resolved in 26f4cef.
