### ISSUE TITLE
[filter enhancement] filter by kimariji/2nd verse text

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#15]
I thought of this because I found it a little annoying to switch to a japanese IME and ctrl f for the poem. It would be nice to have a textbox that auto converts to hiragana that you could use to filter the poems by

This is also something that I could look into implementing if you approve of this change

**Comment by GoldenChrysus** [comment]
This is already planned like I mentioned [in your pull request.](https://github.com/GoldenChrysus/KarutaSRS/pull/13#issuecomment-570714794) However, I would want to add this at the same time learned poem filtering is added to avoid having to rework the UI several times.

**Comment by GoldenChrysus** [comment]
Merged to `master` in commit fd0d95119d1dbf20528c71c77859800b9a71285d. Released in [0.4.0-alpha](https://github.com/GoldenChrysus/KarutaSRS/tree/0.4.0-alpha).
