### ISSUE TITLE
One more inaccurate kimariji

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#16]
Related to #12.

Super sorry, seems like I missed one more. The kimariji for poem 19 in the app is なにはが, but on my cards with the kimariji printed they have なにわが. I quickly went through them all again and I'm pretty sure this is the only one I missed.

**Comment by GoldenChrysus** [comment]
Do you want me to reset this item? You're the only one so far who has learned it, so I can either keep your learned record as it or delete your reviews for you.

**Comment by GoldenChrysus** [comment]
Merged to `master` in commit 36cb604be2e8965efc8b9773c7165a144e32f078. Released in [0.3.1-alpha](https://github.com/GoldenChrysus/KarutaSRS/tree/0.3.1-alpha).

**Comment by kufii** [comment]
Nah it's ok you don't need to bother
