### ISSUE TITLE
minor style issue with filters

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#17]
Hey! Great work on the new filters! just noticed a minor style issue though, at certain widths, the placeholder text for the dropdowns wrap making it look a little off:

![image](https://user-images.githubusercontent.com/4913552/73877686-1915b980-4827-11ea-83b9-00002daeed13.png)

**Comment by GoldenChrysus** [comment]
Thanks. I noticed the wrapping but not the poem sort going out of bounds. I'll probably just shrink the new input boxes since they don't need to be that long when only a handful of characters will be typed at most.

**Comment by GoldenChrysus** [comment]
I think this was resolved via my intended fix communicated above but I forgot to comment which commit resolves? So, uh, closing.
