### ISSUE TITLE
Poem 21 torifuda doesn't look like tournament card

### ISSUE THREAD

**Issue by jeifour** [GoldenChrysus/KarutaSRS#25]
I noticed that poem 21 looks different. I think normally the third row has 6 characters, other than all the other torifuda in a regular deck.

Here's a picture:
![スクリーンショット 2020-12-07 0 37 46](https://user-images.githubusercontent.com/3247063/101296607-971a6680-3824-11eb-8fd8-30489d7faf89.png)

Of course maybe this was deliberate. I imagine it'd be kind of a hassle to change card layout just for a single poem. But I didn't find this documented so I thought I'd let you know.

**Comment by GoldenChrysus** [comment]
Resolved in commit 16486255ea6e53db32775f2a4e9fe5ba71086ac7. To be released in the next version release (current version: `0.4.1-alpha`).
