### ISSUE TITLE
[feature request] filter poems by ones you've learned

### ISSUE THREAD

**Issue by kufii** [GoldenChrysus/KarutaSRS#4]
I was thinking maybe by clicking the poems learned number in your dashboard? Could probably do the same thing with poems mastered but I haven't got any of those yet obviously

**Comment by GoldenChrysus** [comment]
Merged to `master` in commit fd0d95119d1dbf20528c71c77859800b9a71285d. Released in [0.4.0-alpha](https://github.com/GoldenChrysus/KarutaSRS/tree/0.4.0-alpha).
